# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 05:59
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0004_slideimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('img', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='手机端缩略图')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源描述')),
                ('slug_url', models.CharField(default='/', max_length=255, verbose_name='默认网址勿改')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Categary', verbose_name='类别')),
            ],
            options={
                'verbose_name': '文章',
            },
        ),
    ]
